### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by akaniklaus** [zalanborsos/online-variance-reduction#1]
Thank you for this great work! FYI, I am retrieving the following error message while trying to import:
`
AttributeError: type object 'vrb.segment_tree.SegmentTreeSampler' has no attribute '__reduce_cython__'

Also, a question to you. How efficient this is in quickly learning the best policy for sampling especially when sampling mini-batches rather than samples. I have an experiment that converges in less than 3000 steps (mini-batches) with importance sampling (and 2300 steps with some heuristic extensions over that), would this number of steps give enough time to learn the best policy using bandit method and be more effective than the heuristics that I may develop manually?

**Comment by zalanborsos** [comment]
Thanks for raising this issue. It was a python3-cython combined probem. After uninstalling the module and installing it with the updated instructions it should work now.

Regarding the question: in the paper, the guarantees for the sampler are given for choosing samples only; the extension to sampling mini-batches is to sample points in i.i.d fashion. The mini-batch setting is trickier to analyze, but we have nevertheless tested in empirically on k-Means (see paper), where it works well.

The efficiency of the sampler in the mini-batch setting is really problem dependent. An empirical observation is that for problems where there are a few important points that have large effect at the beginning of the optimization (e.g. support vectors in SVM, outliers in k-Means, etc.), the sampler will focus on them due to their large gradients. On the other hand, there are situations where the best sampling distribution in hindsight is the uniform distributions (for example the k-Means experiment on MIST), and thus the sampler does not help.

**Comment by akaniklaus** [comment]
Thank you for your response and again for sharing this useful work! I guess that there is a trade-off there as without mini-batches importance sampling would loose its advantage of faster convergence. I would assume that it would work well especially when mini-batches are smaller but my question was rather in the cases where there may not be enough iterations for the sampler to converge to the best sampling strategy until the model convergence happens. In case of using mini-batches basically (e.g. of 1024 samples) the number of total iterations dramatically reduces. 

I was actually speaking for the case of Deep Learning actually where applying the right sampling strategy can be beneficial not only for faster model convergence, but also for eliminating outliers (I developed a sampling strategy which takes the correlation of loss changes for that) and preventing over-fitting by forcing the model to be perform uniformly across batches, etc.

**Comment by akaniklaus** [comment]
@zalanborsos Dear Zalan, I have made an implementation (in the following link) for a similar problem. 
I would be glad if you can check it and share your feedback as I am not very familiar with this domain:
https://github.com/kayuksel/combinatorial-bandit/

**Comment by akaniklaus** [comment]
@zalanborsos I would also like to share the following paper with you: https://arxiv.org/abs/1901.04215
